services:
  postgres:
    image: postgres:15
    container_name: vespera-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vespera
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    container_name: vespera-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vespera-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio

    environment:
      DB_HOST: postgres
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: vespera
      DB_PORT: 5432 
      DB_SSLMODE: disable 
      BUCKET_PORT: 9000
      BUCKET_NAME: vespera-images
      MINIO_HOST: vespera-minio 
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
      MINIO_PORT: 9000
volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
